# This is a basic workflow to help you get started with Actions

name: Test Scripts

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  read_recent_issue:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: pCYSl5EDgo/cat@master
        id: read_recent
        with:
          path: issues.txt
      - run: echo $TEXT
        env:
          TEXT: ${{ steps.read_recent.outputs.text }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  powershell:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Download Education Issues
        id: educationIssues
        shell: pwsh
        run: ./windows/magpi-education-downloader.ps1
      - name: "Check file existence Windows"
        id: check_files
        uses: andstor/file-existence-action@v1.1.0
        with:
          files: "education_issues/MagPi-EduEdition02.pdf"
          allow_failure: false
      - name: lslah issues
        run: Get-ChildItem –path D:\a\MagPiDownloader\MagPiDownloader\education_issues
      - name: File exists
        if: steps.check_files.outputs.files_exists == 'false'
        run: exit 1

  bash-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Download Education Issues
        id: educationIssues
        run: bash ./linux_mac/magpi-education-downloader.sh
      - name: Download Issues with end limit
        id: normalIssuesWithEndLimit
        run: bash ./linux_mac/magpi-issue-downloader.sh -l 2
      - name: Download Issues with start limit
        id: normalIssuesWithStartLimit
        run: bash ./linux_mac/magpi-issue-downloader.sh -f 99
      - name: Download Issues with start and end limit
        id: normalIssuesWithRange
        run: bash ./linux_mac/magpi-issue-downloader.sh -f 95 -l 96
      - name: Download French Issues
        id: frenchIssues
        run: bash ./linux_mac/magpi-issue-downloader_french.sh
      - name: Download Hebrew Issues
        id: hebrewIssues
        run: bash ./linux_mac/magpi-issue-downloader_hebrew.sh
      - name: Download Italian Issues
        id: italianIssues
        run: bash ./linux_mac/magpi-issue-downloader_italian.sh
      - name: Download Spanish Issues
        id: spanishIssues
        run: bash ./linux_mac/magpi-issue-downloader_spanish.sh
      - name: Download Special Issues
        id: specialIssues
        run: bash ./linux_mac/magpi-special-issue-downloader.sh
      # check if files are existing
      - name: "Check file existence Linux"
        id: check_files
        uses: andstor/file-existence-action@v1.1.0
        with:
          files: "education_issues/MagPi-EduEdition02.pdf"
          allow_failure: false
      - name: lslah
        run: ls -lah  education_issues/
      - name: File exists
        if: steps.check_files.outputs.files_exists == 'false'
        run: exit 1
  bash-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Download Education Issues
        id: educationIssues
        run: bash ./linux_mac/magpi-education-downloader.sh
      - name: Download Issues with end limit
        id: normalIssuesWithEndLimit
        run: bash ./linux_mac/magpi-issue-downloader.sh -l 2
      - name: Download Issues with start limit
        id: normalIssuesWithStartLimit
        run: bash ./linux_mac/magpi-issue-downloader.sh -f 99
      - name: Download Issues with start and end limit
        id: normalIssuesWithRange
        run: bash ./linux_mac/magpi-issue-downloader.sh -f 95 -l 96
      - name: Download French Issues
        id: frenchIssues
        run: bash ./linux_mac/magpi-issue-downloader_french.sh
      - name: Download Hebrew Issues
        id: hebrewIssues
        run: bash ./linux_mac/magpi-issue-downloader_hebrew.sh
      - name: Download Italian Issues
        id: italianIssues
        run: bash ./linux_mac/magpi-issue-downloader_italian.sh
      - name: Download Spanish Issues
        id: spanishIssues
        run: bash ./linux_mac/magpi-issue-downloader_spanish.sh
      - name: Download Special Issues
        id: specialIssues
        run: bash ./linux_mac/magpi-special-issue-downloader.sh
      # check if files are existing
      - name: "Check file existence MacOs"
        id: check_files
        uses: andstor/file-existence-action@v1.1.0
        with:
          files: "education_issues/MagPi-EduEdition02.pdf"
          allow_failure: false
      - name: lslah
        run: ls -lah education_issues
      - name: File exists
        if: steps.check_files.outputs.files_exists == 'false'
        run: exit 1   
