name: Update latest issues

on:
  push:
    branches: [ main ]

jobs:
  bash-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: update issues
        id: updateIssues
        run: bash ./sources-for-download/script-for-using-latest-version.sh
      - name: gitStatus
        run: git status
      - name: catIssue
        run: cat ./sources-for-download/regular-issues.txt
      - name: config git
        run: |
          git config --local user.email "1439809+joergi@users.noreply.github.com"
          git config --local user.name "Joergi via GitHub Actions"
          git commit -am "update to use latest version"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: Automated Pull Request
          body: Automated pull request created by GitHub Actions
          branch: automated_PR_for_update_issues
          branch-suffix: timestamp
          delete-branch: true
          labels: "automerge"
      - name: Auto-merge Pull Request
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          MERGE_LABELS: "automerge"
          MERGE_READY_STATE: "unstable"
          MERGE_DELETE_BRANCH: "true"
          MERGE_FILTER_AUTHOR: "joergi"
          MERGE_RETRIES: "6"
          MERGE_RETRY_SLEEP: "30000"

